### ISSUE TITLE
I Can't execute Pretrain.

### ISSUE THREAD

**Issue by oshita-n** [Ldhlwh/DFMGAN#1]
**Describe the bug**
I get the attached error and can't run pretrain.
I was able to execute up to pre-processing.

**To Reproduce**
1. In '...' directory, run command '...'
```
cd DFMGAN
python train.py --data ./data/hazelnut_good.zip --outdir runs/hazelnut_good --gpus 1 --kimg 3000
```

2. See error (copy&paste full log, including exceptions and **stacktraces**).

```
/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/torch/nn/modules/module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448234945/work/c10/core/TensorImpl.h:1156.)
  return forward_call(*input, **kwargs)
Traceback (most recent call last):
  File "train.py", line 644, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 637, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 472, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/home/oshita-n/github/DFMGAN/training/training_loop.py", line 532, in training_loop
    result_dict = metric_main.calc_metric(metric=metric, G=snapshot_data['G_ema'],
  File "/home/oshita-n/github/DFMGAN/metrics/metric_main.py", line 46, in calc_metric
    results = _metric_dict[metric](opts)
  File "/home/oshita-n/github/DFMGAN/metrics/metric_main.py", line 86, in fid50k_full
    fid = frechet_inception_distance.compute_fid(opts, max_real=None, num_gen=50000)
  File "/home/oshita-n/github/DFMGAN/metrics/frechet_inception_distance.py", line 29, in compute_fid
    mu_gen, sigma_gen = metric_utils.compute_feature_stats_for_generator(
  File "/home/oshita-n/github/DFMGAN/metrics/metric_utils.py", line 280, in compute_feature_stats_for_generator
    features = detector(images, **detector_kwargs)
  File "/home/oshita-n/.pyenv/versions/anaconda3-2022.05/envs/dfmgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: MALFORMED INPUT: lanes dont match
```

**Expected behavior**

- can execute

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 on WSL 
 - PyTorch version: 1.9.0, 1.9.1
 - CUDA toolkit version:  11.6
 - NVIDIA driver version: 526.98 
 - GPU 2090ti
 - use Docker: No
**Additional context**

I would like to know what libraries and OS versions you can reliably run.

**Comment by oshita-n** [comment]
Thank you for your reply.
Yes, the display here is now "Done".
The attached error occurs after this display.

Thank you for sharing your environmental configuration.
I will try again with this.
