### ISSUE TITLE
Could not find MSVC/GCC/CLANG

### ISSUE THREAD

**Issue by justinvo277** [Ldhlwh/DFMGAN#45]
Setting up PyTorch plugin "bias_act_plugin"... Failed!
D:\my_env\DFMGAN\torch_utils\ops\bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "D:\my_env\DFMGAN\torch_utils\ops\bias_act.py", line 48, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "D:\my_env\DFMGAN\torch_utils\custom_ops.py", line 64, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "D:\my_env\DFMGAN\torch_utils\custom_ops.py".

Help me, plsss <3

**Comment by Ldhlwh** [comment]
For plugin issues please refer to the repo of stylegan2-ada-pytorch. It is not an additional requirement from DFMGAN.
