### ISSUE TITLE
请问这个错怎么解决呢RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented

### ISSUE THREAD

**Issue by tanshuai555** [Ldhlwh/DFMGAN#50]
root/project/mzc/ts/DFMGAN/torch_utils/ops/grid_sample_gradfix.py:39: UserWarning: grid_sample_gradfix not supported on PyTorch 1.10.0+cu111. Falling back to torch.nn.functional.grid_sample().
  warnings.warn(f'grid_sample_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.grid_sample().')
/root/project/mzc/ts/DFMGAN/torch_utils/ops/grid_sample_gradfix.py:39: UserWarning: grid_sample_gradfix not supported on PyTorch 1.10.0+cu111. Falling back to torch.nn.functional.grid_sample().
  warnings.warn(f'grid_sample_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.grid_sample().')
/root/project/mzc/ts/DFMGAN/torch_utils/ops/grid_sample_gradfix.py:39: UserWarning: grid_sample_gradfix not supported on PyTorch 1.10.0+cu111. Falling back to torch.nn.functional.grid_sample().
  warnings.warn(f'grid_sample_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.grid_sample().')
/root/project/mzc/ts/DFMGAN/torch_utils/ops/grid_sample_gradfix.py:39: UserWarning: grid_sample_gradfix not supported on PyTorch 1.10.0+cu111. Falling back to torch.nn.functional.grid_sample().
  warnings.warn(f'grid_sample_gradfix not supported on PyTorch {torch.__version__}. Falling back to torch.nn.functional.grid_sample().')
Traceback (most recent call last):
  File "train.py", line 644, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 637, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 472, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/root/project/mzc/ts/DFMGAN/training/training_loop.py", line 424, in training_loop
    gen_defect_z = gen_defect_z, real_mask = real_mask, mask_threshold = G_kwargs.mask_threshold)
  File "/root/project/mzc/ts/DFMGAN/training/loss.py", line 263, in accumulate_gradients
    (real_logits * 0 + loss_Dreal + loss_Dr1).mean().mul(gain).backward()
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/conda/envs/ts_env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented

**Comment by Ldhlwh** [comment]
> UserWarning: grid_sample_gradfix not supported on PyTorch 1.10.0+cu111

看起来是环境没配好的问题
